main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('client_create/', views.ClientCreate.as_view(), name='client_create'),
    path('client_update/<str:pk>/', views.ClientUpdate.as_view(), name='client_update'),
    path('client_delete/<str:pk>/', views.ClientDelete.as_view(), name='client_delete'),

    path('plan_create/', views.PlanCreate.as_view(), name='plan_create'),
    path('plan_update/<str:pk>/', views.PlanUpdate.as_view(), name='plan_update'),
    path('plan_delete/<str:pk>/', views.PlanDelete.as_view(), name='plan_delete'),

    path('phase_create/', views.PhaseCreate.as_view(), name='phase_create'),
    path('phase_update/<str:pk>/', views.PhaseUpdate.as_view(), name='phase_update'),
    path('phase_delete/<str:pk>/', views.PhaseDelete.as_view(), name='phase_delete'),

    path('strategy_create/', views.StrategyCreate.as_view(), name='strategy_create'),
    path('strategy_update/<str:pk>/', views.StrategyUpdate.as_view(), name='strategy_update'),
    path('strategy_delete/<str:pk>/', views.StrategyDelete.as_view(), name='strategy_delete'),

    path('country_create/', views.CountryCreate.as_view(), name='country_create'),
    path('country_update/<str:pk>/', views.CountryUpdate.as_view(), name='country_update'),
    path('country_delete/<str:pk>/', views.CountryDelete.as_view(), name='country_delete'),

    path('channel_create/', views.ChannelCreate.as_view(), name='channel_create'),
    path('channel_update/<str:pk>/', views.ChannelUpdate.as_view(), name='channel_update'),
    path('channel_delete/<str:pk>/', views.ChannelDelete.as_view(), name='channel_delete'),

    path('ad_create/', views.AdCreate.as_view(), name='ad_create'),
    path('ad_update/<str:pk>/', views.AdUpdate.as_view(), name='ad_update'),
    path('ad_delete/<str:pk>/', views.AdDelete.as_view(), name='ad_delete'),

    path('targetcountry_create/', views.TargetCountryCreate.as_view(), name='targetcountry_create'),
    path('targetcountry_update/<str:pk>/', views.TargetCountryUpdate.as_view(), name='targetcountry_update'),
    path('targetcountry_delete/<str:pk>/', views.TargetCountryDelete.as_view(), name='targetcountry_delete'),

    path('targetchannel_create/', views.TargetChannelCreate.as_view(), name='targetchannel_create'),
    path('targetchannel_update/<str:pk>/', views.TargetChannelUpdate.as_view(), name='targetchannel_update'),
    path('targetchannel_delete/<str:pk>/', views.TargetChannelDelete.as_view(), name='targetchannel_delete'),

]

media/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
# from tkinter import CASCADE
from tkinter import Widget
from django.db import models
import datetime

class Client(models.Model):
	client_name = models.CharField(max_length=200, null=True)

	def __str__(self) -> str:
		return self.client_name

class Plan(models.Model):
	plan_name = models.CharField(max_length=200, null=True)
	client = models.ForeignKey(Client, null=True, on_delete=models.CASCADE)

	def __str__(self) -> str:
		return self.plan_name

class Phase(models.Model):
	phase_name = models.CharField(max_length=200, null=True)
	phase_start_date = models.DateField(default=datetime.date.today)
	phase_end_date = models.DateField(default=datetime.date.today)
	plan = models.ForeignKey(Plan, null=True, on_delete=models.CASCADE)
	
	def __str__(self) -> str:
		return self.phase_name

class Strategy(models.Model):
	strategy_name = models.CharField(max_length=200, null=True)
	strategy_start_date = models.DateField(default=datetime.date.today)
	strategy_end_date = models.DateField(default=datetime.date.today)
	phase = models.ForeignKey(Phase, null=True, on_delete=models.CASCADE)

	def __str__(self) -> str:
		return self.strategy_name

class Country(models.Model):
	country_name = models.CharField(max_length=200, null=True)
	targetcountries = models.ManyToManyField(Strategy, through='TargetCountry')

	def __str__(self) -> str:
		return self.country_name

class TargetCountry(models.Model):
	strategy = models.ForeignKey(Strategy, null=True, on_delete=models.CASCADE)
	country = models.ForeignKey(Country, null=True, on_delete=models.CASCADE)
	
	def __str__(self) -> str:
		return (f'{self.strategy}:{self.country}')

class Channel(models.Model):
	channel_name = models.CharField(max_length=200, null=True)
	targetchannels = models.ManyToManyField(TargetCountry, through='TargetChannel')
	
	def __str__(self) -> str:
		return self.channel_name

class TargetChannel(models.Model):
	targetcountry = models.ForeignKey(TargetCountry, null=True, on_delete=models.CASCADE)
	channel = models.ForeignKey(Channel, null=True, on_delete=models.CASCADE)

	def __str__(self) -> str:
		return (f'{self.targetcountry}:{self.channel}')

class Ad(models.Model):
	ad_name = models.CharField(max_length=200, null=True)

	def __str__(self) -> str:
		return self.ad_name

class ChannelAd(models.Model):
	channel = models.ForeignKey(Channel, null=True, on_delete=models.CASCADE)
	ad = models.ForeignKey(Ad, null=True, on_delete=models.CASCADE)
	
	def __str__(self) -> str:
		return (f'{self.channel}:{self.ad}')

main/forms.py
from sqlite3 import Date
from django import forms
from django.forms import ModelForm
from .models import Client, Plan, Phase, Strategy, Country, Channel, Ad, TargetCountry, TargetChannel

class DateInput(forms.DateInput):
    input_type = 'date'

class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ['client_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['client_name'].widget.attrs['autofocus'] = 'on'

class PlanForm(ModelForm):
    class Meta:
        model = Plan
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['client'].widget.attrs['autofocus'] = 'on'

class PhaseForm(ModelForm):
    class Meta:
        model = Phase
        fields = '__all__'
        widgets = {
                'phase_start_date': DateInput(),
                'phase_end_date': DateInput()
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['plan'].widget.attrs['autofocus'] = 'on'
        
class StrategyForm(ModelForm):
    class Meta:
        model = Strategy
        fields = '__all__'
        widgets = {
            'strategy_start_date': DateInput(),
            'strategy_end_date': DateInput()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phase'].widget.attrs['autofocus'] = 'on'

class CountryForm(ModelForm):
    class Meta:
        model = Country
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['country_name'].widget.attrs['autofocus'] = 'on'

class ChannelForm(ModelForm):
    class Meta:
        model = Channel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['channel_name'].widget.attrs['autofocus'] = 'on'

class AdForm(ModelForm):
    class Meta:
        model = Ad
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ad_name'].widget.attrs['autofocus'] = 'on'

class TargetCountryForm(ModelForm):
    class Meta:
        model = TargetCountry
        fields = '__all__'

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['strategy_name'].widget.attrs['autofocus'] = 'on'

class TargetChannelForm(ModelForm):
    class Meta:
        model = TargetChannel
        fields = '__all__'

main/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.urls import reverse_lazy
from .forms import ClientForm, PlanForm, PhaseForm, StrategyForm, CountryForm, ChannelForm, AdForm, TargetCountryForm, TargetChannelForm
from .models import *
from django.views.generic.list import ListView
from django.views.generic import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
# from bootstrap_datepicker_plus.widgets import DatePickerInput

# messages.warning(request, 'Watch Out!!!')

class Dashboard(ListView):
    model = Client
    template_name = 'main/dashboard.html'
    context_object_name = 'clients'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['plans'] = Plan.objects.all()
        context['phases'] = Phase.objects.all()
        context['strategies'] = Strategy.objects.all()
        context['targetcountries'] = TargetCountry.objects.all()
        context['targetchannels'] = TargetChannel.objects.all()
        context['countries'] = Country.objects.all()
        context['channels'] = Channel.objects.all()
        context['ads'] = Ad.objects.all()
        return context

# Client
class ClientCreate(CreateView):
    template_name = 'main/client_create.html'
    model = Client
    form_class = ClientForm
    context_object_name = 'client'
    success_url= reverse_lazy('main:dashboard')

class ClientDelete(DeleteView):
    template_name = 'main/client_delete.html'
    model = Client
    context_object_name = 'client'
    success_url= reverse_lazy('main:dashboard')

class ClientUpdate(UpdateView):
    template_name = 'main/client_update.html'
    model = Client
    form_class = ClientForm
    context_object_name = 'client'
    success_url= reverse_lazy('main:dashboard')

# Plan
class PlanCreate(CreateView):
    template_name = 'main/plan_create.html'
    model = Plan
    form_class = PlanForm
    context_object_name = 'plan'
    success_url= reverse_lazy('main:dashboard')

class PlanDelete(DeleteView):
    template_name = 'main/plan_delete.html'
    model = Plan
    context_object_name = 'plan'
    success_url= reverse_lazy('main:dashboard')

class PlanUpdate(UpdateView):
    template_name = 'main/plan_update.html'
    model = Plan
    form_class = PlanForm
    context_object_name = 'plan'
    success_url= reverse_lazy('main:dashboard')

# Phase
class PhaseCreate(CreateView):
    template_name = 'main/phase_create.html'
    model = Phase
    form_class = PhaseForm
    context_object_name = 'phase'
    success_url= reverse_lazy('main:dashboard')

class PhaseDelete(DeleteView):
    template_name = 'main/phase_delete.html'
    model = Phase
    context_object_name = 'phase'
    success_url= reverse_lazy('main:dashboard')

class PhaseUpdate(UpdateView):
    template_name = 'main/phase_update.html'
    model = Phase
    form_class = PhaseForm
    context_object_name = 'phase'
    success_url= reverse_lazy('main:dashboard')

# Strategy
class StrategyCreate(CreateView):
    template_name = 'main/strategy_create.html'
    model = Strategy
    form_class = StrategyForm
    context_object_name = 'strategy'
    success_url= reverse_lazy('main:dashboard')

class StrategyDelete(DeleteView):
    template_name = 'main/strategy_delete.html'
    model = Strategy
    context_object_name = 'strategy'
    success_url= reverse_lazy('main:dashboard')

class StrategyUpdate(UpdateView):
    template_name = 'main/strategy_update.html'
    model = Strategy
    form_class = StrategyForm
    context_object_name = 'strategy'
    success_url= reverse_lazy('main:dashboard')

# Country
class CountryCreate(CreateView):
    template_name = 'main/country_create.html'
    model = Country
    form_class = CountryForm
    context_object_name = 'country'
    success_url= reverse_lazy('main:dashboard')

class CountryDelete(DeleteView):
    template_name = 'main/country_delete.html'
    model = Country
    context_object_name = 'country'
    success_url= reverse_lazy('main:dashboard')

class CountryUpdate(UpdateView):
    template_name = 'main/country_update.html'
    model = Country
    form_class = CountryForm
    context_object_name = 'channel'
    success_url= reverse_lazy('main:dashboard')

# Channel
class ChannelCreate(CreateView):
    template_name = 'main/channel_create.html'
    model = Channel
    form_class = ChannelForm
    context_object_name = 'channel'
    success_url= reverse_lazy('main:dashboard')

class ChannelDelete(DeleteView):
    template_name = 'main/channel_delete.html'
    model = Channel
    context_object_name = 'channel'
    success_url= reverse_lazy('main:dashboard')

class ChannelUpdate(UpdateView):
    template_name = 'main/channel_update.html'
    model = Channel
    form_class = ChannelForm
    context_object_name = 'channel'
    success_url= reverse_lazy('main:dashboard')
        
# Ad
class AdCreate(CreateView):
    template_name = 'main/ad_create.html'
    model = Ad
    form_class = AdForm
    context_object_name = 'ad'
    success_url= reverse_lazy('main:dashboard')

class AdDelete(DeleteView):
    template_name = 'main/ad_delete.html'
    model = Ad
    context_object_name = 'ad'
    success_url= reverse_lazy('main:dashboard')

class AdUpdate(UpdateView):
    template_name = 'main/ad_update.html'
    model = Ad
    form_class = AdForm
    context_object_name = 'ad'
    success_url= reverse_lazy('main:dashboard')

# TargetCountry
class TargetCountryCreate(CreateView):
    template_name = 'main/targetcountry_create.html'
    model = TargetCountry
    form_class = TargetCountryForm
    context_object_name = 'targetcountry'
    success_url= reverse_lazy('main:dashboard')

class TargetCountryDelete(DeleteView):
    template_name = 'main/targetcountry_delete.html'
    model = TargetCountry
    context_object_name = 'targetcountry'
    success_url= reverse_lazy('main:dashboard')

class TargetCountryUpdate(UpdateView):
    template_name = 'main/targetcountry_update.html'
    model = TargetCountry
    form_class = TargetCountryForm
    context_object_name = 'targetcountry'
    success_url= reverse_lazy('main:dashboard')

# TargetChannel
class TargetChannelCreate(CreateView):
    template_name = 'main/targetchannel_create.html'
    model = TargetChannel
    form_class = TargetChannelForm
    context_object_name = 'targetchannel'
    success_url= reverse_lazy('main:dashboard')

class TargetChannelDelete(DeleteView):
    template_name = 'main/targetchannel_delete.html'
    model = TargetCountry
    context_object_name = 'targetchannel'
    success_url= reverse_lazy('main:dashboard')

class TargetChannelUpdate(UpdateView):
    template_name = 'main/targetchannel_update.html'
    model = TargetChannel
    form_class = TargetChannelForm
    context_object_name = 'targetchannel'
    success_url= reverse_lazy('main:dashboard')

main/templates/old/client_form.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}
<div class="row">
    <form action="/create_client/" method="POST">
        {% csrf_token %}
        {{client_form.as_p}}
        {{plan_form.as_p}}
        {{phase_form.as_p}}
        {{strategy_form.as_p}}
        <button class="btn btn-primary" type="submit">Create</button>
    </form>
</div>

{% endblock %}



main/templates/old/dashboard a links.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}

<div class="row mt-5">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title font-monospace">DASHBOARD</h5>
            <ul class="nav nav-tabs card-header-tabs" data-bs-tabs="tabs" role="tablist" id="tabs">
                <li class="nav-item" role="presentation">
                    <a class="nav-link active show font-monospace" aria-current="true" data-bs-toggle="tab" href="#clients">CLIENTS</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link font-monospace" data-bs-toggle="tab" href="#plans">PLANS</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link font-monospace" data-bs-toggle="tab" href="#phases">PHASES</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link font-monospace" data-bs-toggle="tab" href="#strategies">STRATEGIES</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link font-monospace" data-bs-toggle="tab" href="#channels">CHANNELS</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link font-monospace" data-bs-toggle="tab" href="#countries">COUNTRIES</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link font-monospace" data-bs-toggle="tab" href="#ads">ADS</a>
                </li>
            </ul>
        </div>

        <div class="card-body tab-content">
            
            <div class="tab-pane fade in show active" role="tabpanel" id="clients">
                <a class="btn btn-primary d-grid" aria-current="page" href="{% url 'main:client_create' %}">Create Client</a>
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th class="col-10"><div class="font-monospace">Client</div></th>
                            <th class="col-1"><div class="text-center font-monospace">Update</div></th>
                            <th class="col-1"><div class="text-center font-monospace">Delete</div></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for client in clients %}
                        <tr>
                            <th scope="row">{{client.client_name}}</th>
                            <td><a class="btn btn-sm btn-secondary d-grid gap-1 text-white" aria-current="page" href="{% url 'main:client_update' client.id %}">Update</a></td>
                            <td><a class="btn btn-sm btn-danger d-grid gap-1" aria-current="page" href="{% url 'main:client_delete' client.id %}">Delete</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="tab-pane fade" role="tabpanel" id="plans">
                <a class="btn btn-primary d-grid" aria-current="page" href="{% url 'main:plan_create' %}">Create Plan</a>
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th class="col-5"><div class="font-monospace">Client</div></th>
                            <th class="col-5"><div class="font-monospace">Plan</div></th>
                            <th class="col-1"><div class="text-center font-monospace">Update</div></th>
                            <th class="col-1"><div class="text-center font-monospace">Delete</div></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for plan in plans %}
                        <tr>
                            <th scope="row">{{plan.client}}</th>
                            <td>{{plan.plan_name}}</td>
                            <td><a class="btn btn-sm btn-secondary d-grid gap-1 text-white" aria-current="page" href="{% url 'main:plan_create' %}">Update</a></td>
                            <td><a class="btn btn-sm btn-danger d-grid gap-1" aria-current="page" href="{% url 'main:plan_create' %}">Delete</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="tab-pane fade" role="tabpanel" id="phases">
                <a class="btn btn-primary d-grid" aria-current="page" href="{% url 'main:client_create' %}">Create Phase</a>
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th class="col-5"><div class="font-monospace">Plan</div></th>
                            <th class="col-5"><div class="font-monospace">Phase</div></th>
                            <th class="col-1"><div class="text-center font-monospace">Update</div></th>
                            <th class="col-1"><div class="text-center font-monospace">Delete</div></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for phase in phases %}
                        <tr>
                            <th scope="row">{{phase.plan}}</th>
                            <td>{{phase.phase_name}}</td>
                            <td><a class="btn btn-sm btn-secondary d-grid gap-1 text-white" aria-current="page" href="{% url 'main:client_create' %}">Update</a></td>
                            <td><a class="btn btn-sm btn-danger d-grid gap-1" aria-current="page" href="{% url 'main:client_create' %}">Delete</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="tab-pane fade" role="tabpanel" id="strategies">
                <a class="btn btn-primary d-grid" aria-current="page" href="{% url 'main:client_create' %}">Create Strategy</a>
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th class="col-5"><div class="font-monospace">Phase</div></th>
                            <th class="col-5"><div class="font-monospace">Strategy</div></th>
                            <th class="col-1"><div class="text-center font-monospace">Update</div></th>
                            <th class="col-1"><div class="text-center font-monospace">Delete</div></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for strategy in strategies %}
                        <tr>
                            <th scope="row">{{strategy.phase}}</th>
                            <td>{{strategy.strategy_name}}</td>
                            <td><a class="btn btn-sm btn-secondary d-grid gap-1 text-white" aria-current="page" href="{% url 'main:client_create' %}">Update</a></td>
                            <td><a class="btn btn-sm btn-danger d-grid gap-1" aria-current="page" href="{% url 'main:client_create' %}">Delete</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

{% endblock %}

main/templates/old/dashboardold.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}

<div class="row mt-5">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <h4 class="card-header font-monospace">CLIENTS</h4>
                <div class="card-body overflow-auto" style="height: 15rem;">
                    <a class="btn btn-primary d-grid" aria-current="page" href="{% url 'main:create_client' %}">Create Client</a>
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th scope="col-2"><div class="text-center font-monospace">Client</div></th>
                                <th scope="col-2"><div class="text-center font-monospace">Update</div></th>
                                <th scope="col-2"><div class="text-center font-monospace">Delete</div></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for client in clients %}
                            <tr>
                                <th scope="row">{{client.client_name}}</th>
                                <td><a class="btn btn-sm btn-secondary d-grid gap-1 text-white" aria-current="page" href="{% url 'main:create_client' %}">Update</a></td>
                                <td><a class="btn btn-sm btn-danger d-grid gap-1" aria-current="page" href="{% url 'main:delete_client' client.id %}">Delete</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-6">
            <div class="card">
                <h4 class="card-header font-monospace">PLANS</h4>
                <div class="card-body overflow-auto" style="height: 15rem;">
                    <a class="btn btn-primary d-grid" aria-current="page" href="{% url 'main:create_plan' %}">Create Plan</a>
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th scope="col-2"><div class="text-center font-monospace">Client</div></th>
                                <th scope="col-2"><div class="text-center font-monospace">Plan</div></th>
                                <th scope="col-2"><div class="text-center font-monospace">Update</div></th>
                                <th scope="col-2"><div class="text-center font-monospace">Delete</div></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for plan in plans %}
                            <tr>
                                <th scope="row">{{plan.client}}</th>
                                <td>{{plan.plan_name}}</td>
                                <td><a class="btn btn-sm btn-secondary d-grid gap-1 text-white" aria-current="page" href="{% url 'main:create_client' %}">Update</a></td>
                                <td><a class="btn btn-sm btn-danger d-grid gap-1" aria-current="page" href="{% url 'main:create_client' %}">Delete</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-6">
           <div class="card">
            <h4 class="card-header font-monospace">PHASES</h4>
            <div class="card-body overflow-auto" style="height: 15rem;">
                <a class="btn btn-primary d-grid" aria-current="page" href="{% url 'main:create_phase' %}">Create Phase</a>
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col-2"><div class="text-center font-monospace">Plan</div></th>
                            <th scope="col-2"><div class="text-center font-monospace">Phase</div></th>
                            <th scope="col-2"><div class="text-center font-monospace">Update</div></th>
                            <th scope="col-2"><div class="text-center font-monospace">Delete</div></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for phase in phases %}
                        <tr>
                            <th scope="row">{{phase.plan}}</th>
                            <td>{{phase.phase_name}}</td>
                            <td><a class="btn btn-sm btn-secondary d-grid gap-1 text-white" aria-current="page" href="{% url 'main:create_client' %}">Update</a></td>
                            <td><a class="btn btn-sm btn-danger d-grid gap-1" aria-current="page" href="{% url 'main:create_client' %}">Delete</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>
        </div>
    
        <div class="col-6">
            <div class="card">
                <h4 class="card-header font-monospace">STRATEGIES</h4>
                <div class="card-body overflow-auto" style="height: 15rem;">
                    <a class="btn btn-primary d-grid" aria-current="page" href="{% url 'main:create_strategy' %}">Create strategy</a>
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th scope="col-2"><div class="text-center font-monospace">Phase</div></th>
                                <th scope="col-2"><div class="text-center font-monospace">Strategy</div></th>
                                <th scope="col-2"><div class="text-center font-monospace">Update</div></th>
                                <th scope="col-2"><div class="text-center font-monospace">Delete</div></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for strategy in strategies %}
                            <tr>
                                <th scope="row">{{strategy.phase}}</th>
                                <td>{{strategy.strategy_name}}</td>
                                <td><a class="btn btn-sm btn-secondary d-grid gap-1 text-white" aria-current="page" href="{% url 'main:create_client' %}">Update</a></td>
                                <td><a class="btn btn-sm btn-danger d-grid gap-1" aria-current="page" href="{% url 'main:create_client' %}">Delete</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/old/phase_form.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <button class="btn btn-primary" type="submit">Create</button>
</form>

{% endblock %}

main/templates/old/plan_form.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form.client}}
    {{form.plan_name}}
    <button class="btn btn-primary" type="submit">Create</button>
</form>

{% endblock %}

main/templates/old/strategy_form.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <button class="btn btn-primary" type="submit">Create</button>
</form>

{% endblock %}

